services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost" ]
      interval: 2s
      timeout: 1s
      retries: 5